[package]
name = "conda-leaves"
version = "0.0.1"
authors = ["lukaszKielar <kielar.lukasz@hotmail.com>"]
edition = "2018"

[dependencies]
colored = "2"
serde = { version = "1.0", features  = ["derive"] }
serde_json = "1.0"
dotenv = "0.15.0"
log = "0.4"
env_logger = "0.7.1"
regex = "1.3.9"
lazy_static = "1.4.0"
glob = "0.3.0"
