name: Validate-PR

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/cargo@1
        with:
          command: test
          args: --release
      - uses: actions-rs/clippy-check@v1
        with:
          args: --all-features
