name: Validate-PR

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: cargo-test
        uses: actions-rs/cargo@v1.0.1
        with:
          command: test
          args: --release
